name: cossea's blog
description: cossea blog
meta_description: "cossea's blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'cossea.github.io'
author:         'cossea'
