name: ximalaya's blog
description: team blog
meta_description: "ximalaya's blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'ximalaya.github.io'
author:         'ximalaya'
